apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-oondemand-homolog
  namespace: central-oondemand-homolog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-oondemand-homolog
  template:
    metadata:
      labels:
        app: central-oondemand-homolog
    spec:
      containers:
        - name: central-oondemand-homolog-container
          image: ghcr.io/oondemand/central-oondemand:${IMAGE_TAG}-homolog
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "2048Mi"
              cpu: "2"
          env:
            - name: NODE_ENV
              value: "${NODE_ENV}"
            - name: SERVICE_NAME
              value: "${SERVICE_NAME}"
            - name: PORT
              value: "${PORT}"
            - name: DB_SERVER
              value: "${DB_SERVER}"
            - name: DB_USER
              value: "${DB_USER}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: DB_NAME
              value: "${DB_NAME}"
            - name: DB_AUTH_SOURCE
              value: "${DB_AUTH_SOURCE}"
            - name: DB_REPLICA_SET
              value: "${DB_REPLICA_SET}"
            - name: DB_TSL
              value: "${DB_TSL}"
            - name: API_OMIE
              value: "${API_OMIE}"
            - name: JWT_SECRET
              value: "${JWT_SECRET}"
            - name: BASE_URL_CST
              value: "${BASE_URL_CST}"
            - name: BASE_URL_APP_PUBLISHER
              value: "${BASE_URL_APP_PUBLISHER}"
